name: Testes Automatizados

on:
  pull_request:
    branches:
      - main

jobs:
  rodar-testes:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install pytest

      - name: Executar testes
        run: pytest
